# Generated by Django 3.1.2 on 2020-10-28 20:04

from django.db import migrations, models
import django.db.models.deletion
import snippets.admin.admin


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('ordering', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('status', models.SmallIntegerField(choices=[(0, 'Черновик'), (1, 'Публичный'), (2, 'Скрытый')], default=1, verbose_name='Статус')),
                ('work_title', models.CharField(db_index=True, max_length=255, verbose_name='Рабочий заголовок')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('slug', models.SlugField(help_text='Латинские буквы и цифры, подчеркивание и дефис', verbose_name='Алиас')),
                ('is_global', models.BooleanField(default=False, verbose_name='Глобальное')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
                'ordering': ('ordering',),
            },
            bases=(snippets.admin.admin.SuperUserDeletableAdminMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copyrights', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Копирайт')),
                ('copyrights_ru', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Копирайт')),
                ('copyrights_en', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Копирайт')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('ordering', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('status', models.SmallIntegerField(choices=[(0, 'Черновик'), (1, 'Публичный'), (2, 'Скрытый')], default=1, verbose_name='Статус')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('url', models.CharField(max_length=255, verbose_name='Ссылка')),
                ('url_ru', models.CharField(max_length=255, null=True, verbose_name='Ссылка')),
                ('url_en', models.CharField(max_length=255, null=True, verbose_name='Ссылка')),
                ('class_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='CSS-класс для ссылки (а):')),
                ('child_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_items', to='vars.menu', verbose_name='Дочернее меню')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='vars.menu', verbose_name='Меню')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Пункты меню',
                'ordering': ('ordering',),
            },
            bases=(snippets.admin.admin.SuperUserDeletableAdminMixin, models.Model),
        ),
    ]
